// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEGUbZNBEc4Zm-weD2wv-iy-rjvpNBgw',
    appId: '1:34869881018:web:c8826c575cc296c908fa83',
    messagingSenderId: '34869881018',
    projectId: 'asroostore-d0197',
    authDomain: 'asroostore-d0197.firebaseapp.com',
    storageBucket: 'asroostore-d0197.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAisqwDjUwPytKKCCnG18cjcE4LwMWZJSA',
    appId: '1:34869881018:android:90d1ecdce331640908fa83',
    messagingSenderId: '34869881018',
    projectId: 'asroostore-d0197',
    storageBucket: 'asroostore-d0197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5m67LGbjOgkh8hsHrLBwca5-cTrLtc5Q',
    appId: '1:34869881018:ios:5c09c8d1770323c408fa83',
    messagingSenderId: '34869881018',
    projectId: 'asroostore-d0197',
    storageBucket: 'asroostore-d0197.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5m67LGbjOgkh8hsHrLBwca5-cTrLtc5Q',
    appId: '1:34869881018:ios:5c09c8d1770323c408fa83',
    messagingSenderId: '34869881018',
    projectId: 'asroostore-d0197',
    storageBucket: 'asroostore-d0197.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEGUbZNBEc4Zm-weD2wv-iy-rjvpNBgw',
    appId: '1:34869881018:web:1463a70bc702878008fa83',
    messagingSenderId: '34869881018',
    projectId: 'asroostore-d0197',
    authDomain: 'asroostore-d0197.firebaseapp.com',
    storageBucket: 'asroostore-d0197.firebasestorage.app',
  );
}
